name: WandoriaLoot
version: '${version}'
main: me.einjojo.wandorialoot.WandoriaLoot
api-version: 1.19
depend: [ ProtocolLib ]
commands:
  lootSetup:
    description: setup
  test:
    description: test