name: WandoriaLoot
version: '${version}'
main: me.einjojo.wandorialoot.WandoriaLoot
api-version: 1.19
depend: [ ProtocolLib ]
commands:
  setup:
    aliases:
      - wandorialootsetup
      - lc
      - lootchest
    description: setup